---
title: "report_GeomTimeline"
autor: "Emilio Garcia"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{report_GeomTimeline}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

1. Load data.

2. Displays the earthquakes timeline as points in a plot.


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(MSDCProjectS)
```

```{r}
path <- "data/earthquakes-2021-05-02_07-20-17_-0400.tsv"
table_original <- read.table(file = path, sep = '\t', header = TRUE)
table <-eq_clean_data(table_original)
table_example <- dplyr::filter(table, lubridate::year(Date) > 2000,
                               Country %in% c("CHINA","JAPAN"))
table_example <- dplyr::select(table_example,Date,Country,Mag,Deaths,Location.Name)
```


```{r}
ggplot2::ggplot(table_example) +
  ggplot2::layer(geom = GeomTimeline,
                 mapping = ggplot2::aes(x = Date,
                                        y = Country,
                                        size = Mag,
                                        color = Deaths),
                 data = table_example,
                 stat = 'identity',
                 position = 'identity',
                 show.legend = NA,
                 inherit.aes = TRUE,
                 params = list(na.rm = FALSE))
```
